<div class="row justify-content-center mt-5">
<div class="col-md-4 col-sm-8 col-xs-12">
    <h1>Sign In</h1>
    <?php echo $this->flash->output(); ?>
    <?php echo \Phalcon\Tag::form(['auth/authorize', 'id' => 'loginForm']) ?>
    <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>' value='<?php echo $this->security->getToken() ?>'/>
        <div class="form-group mb-3">
            <label for="email">Email address</label>
            <?php echo \Phalcon\Tag::emailField(['email', 'placeholder' => '', 'class' => 'form-control']) ?>
        </div>
        <div class="form-group mb-3">
            <label for="password">Password</label>
            <?php echo \Phalcon\Tag::passwordField(['password', 'placeholder' => '', 'class' => 'form-control']) ?>
        </div>
        <button type="submit" class="btn btn-primary" value="Submit">Submit</button>
        <?php echo \Phalcon\Tag::linkTo(['auth/signup', 'Create New Account', 'class' => 'float-end']); ?>
    </form>
</div>
</div>